# Generated by Django 4.0 on 2021-12-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alumnos_rename_curso_cursos_rename_jugador_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
