# Generated by Django 4.0 on 2021-12-19 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='Instrumento',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
