# Generated by Django 4.0 on 2021-12-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_profesores_instrumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='Instrumento',
            new_name='instrumento',
        ),
    ]
